import type { Metadata } from 'next'
import Image from 'next/image'
import './globals.css'
import styles from '@/app/home.module.css'
import Link from 'next/link'
import logo from '@/images/logo.png'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
	weight: '400',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={roboto.className}>
			<body>
				<div className={styles.header}>
					<Link href="/">
						<Image src={logo} alt="logo" width={100} height={100} />
					</Link>
					<Link href="/" className={styles.link}>
						Домашня сторінка
					</Link>
					<Link href="#" className={styles.link}>
						Суші
					</Link>
					<Link href="#" className={styles.link}>
						Піца
					</Link>
					<Link href="#" className={styles.link}>
						Напої
					</Link>
					<Link href="#" className={styles.link}>
						Вхід/реєстрація
					</Link>
				</div>
				{children}
			</body>
		</html>
	)
}
