import type { Metadata } from 'next'
import Image from 'next/image'
import './globals.css'
import styles from '@/app/home.module.css'
import Link from 'next/link'
import logo from '../../public/images/logo.png'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
	weight: '400',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Sho Tam Sushi',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={roboto.className}>
			<body>
				<div className={styles.wrapper}>
					<div className={styles.header}>
						<Link href="/" className={styles.logo}>
							<Image src={logo} alt="logo" width={100} height={100} />
						</Link>
						<div className={styles.links}>
							<Link href="/" className={styles.link}>
								Домашня сторінка
							</Link>
							<Link href="#" className={styles.link}>
								Суші
							</Link>
							<Link href="#" className={styles.link}>
								Піца
							</Link>
							<Link href="#" className={styles.link}>
								Напої
							</Link>
						</div>
						<Link href="/register" className={styles.link}>
							Вхід/реєстрація
						</Link>
					</div>
					<div className="content">{children}</div>
					<div className={styles.footer}>
						<h1>Footer</h1>
					</div>
				</div>
			</body>
		</html>
	)
}
